In [4]:
import torch

In [6]:
x = torch.empty(4, 2)
print(x)

tensor([[-3.8168e-06,  2.1118e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])


In [7]:
x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [8]:
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [13]:
x = x.new_ones(2, 4, dtype=torch.double) # 타입 변환
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [14]:
x = torch.randn_like(x, dtype=float)
print(x)

tensor([[-0.1444, -0.3261, -0.6770,  0.3874],
        [ 0.4013,  0.1717,  0.7338,  0.9191]], dtype=torch.float64)


In [15]:
print(x.size())

torch.Size([2, 4])


In [16]:
ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [17]:
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [18]:
it = torch.IntTensor([1,2,3])
print(it.dtype)

torch.int32


In [20]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


In [22]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-1.1262])
-1.1261682510375977
torch.float32


In [23]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y = torch.ones_like(x, device=device)
print(y)
x = x.to(device)
print(x)
z = x + y
print(z)
print(z.to('cpu', torch.double))

cpu
tensor([1.])
tensor([-1.1262])
tensor([-0.1262])
tensor([-0.1262], dtype=torch.float64)


In [25]:
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [26]:
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [28]:
t2 = torch.tensor([ [1,2,3],
                    [4,5,6],
                    [7,8,9] ])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [31]:
t3 = torch.tensor([[[1,2,3],
                    [4,5,6],
                    [7,8,9]],
                    [[1,2,3],
                    [4,5,6],
                    [7,8,9]],
                    [[1,2,3],
                    [4,5,6],
                    [7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [32]:
import math

In [40]:
x = torch.rand(1, 2) * 2 - 1
print(x)
print(torch.abs(x))
print(torch.ceil(x)) # 올림
print(torch.floor(x)) # 내림
print(torch.clamp(x, -0.5, 0.5)) # 최대, 최소값 한정

tensor([[-0.8315,  0.9428]])
tensor([[0.8315, 0.9428]])
tensor([[-0., 1.]])
tensor([[-1.,  0.]])
tensor([[-0.5000,  0.5000]])


In [42]:
print(torch.min(x))
print(torch.max(x))
print(torch.mean(x))
print(torch.std(x)) # 표준편차
print(torch.prod(x))
print(torch.unique(torch.tensor([1,2,3,1,2,2,]))) # 중복을 제거함

tensor(-0.8315)
tensor(0.9428)
tensor(0.0557)
tensor(1.2546)
tensor(-0.7839)
tensor([1, 2, 3])


In [47]:
x = torch.rand(2, 2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))

tensor([[0.8612, 0.3039],
        [0.5661, 0.5073]])
torch.return_types.max(
values=tensor([0.8612, 0.5073]),
indices=tensor([0, 1]))
torch.return_types.max(
values=tensor([0.8612, 0.5661]),
indices=tensor([0, 0]))


In [49]:
x = torch.rand(2, 2)
print(x)
print(x.min(dim=0))
print(x.min(dim=1))

tensor([[0.7907, 0.8693],
        [0.0285, 0.1338]])
torch.return_types.min(
values=tensor([0.0285, 0.1338]),
indices=tensor([1, 1]))
torch.return_types.min(
values=tensor([0.7907, 0.0285]),
indices=tensor([0, 0]))


In [50]:
x = torch.rand(2, 2)
print(x)
y = torch.rand(2, 2)
print(y)

tensor([[0.0698, 0.0101],
        [0.6450, 0.7239]])
tensor([[0.8103, 0.1495],
        [0.7829, 0.3845]])


In [51]:
print(x + y)
print(torch.add(x, y))

tensor([[0.8801, 0.1596],
        [1.4279, 1.1085]])
tensor([[0.8801, 0.1596],
        [1.4279, 1.1085]])


In [54]:
result = torch.empty(2, 2)
torch.add(x, y, out=result)
print(result)

tensor([[0.8801, 0.1596],
        [1.4279, 1.1085]])


In [56]:
print(x)
print(y)
y.add_(x) # y += x
print(y)

tensor([[0.0698, 0.0101],
        [0.6450, 0.7239]])
tensor([[0.8801, 0.1596],
        [1.4279, 1.1085]])
tensor([[0.9499, 0.1697],
        [2.0729, 1.8324]])


In [59]:
print(x)
print(y)
print(x - y)
print(torch.sub(x, y))
print(x.sub(y))

tensor([[-0.8801, -0.1596],
        [-1.4279, -1.1085]])
tensor([[0.9499, 0.1697],
        [2.0729, 1.8324]])
tensor([[-1.8300, -0.3294],
        [-3.5008, -2.9408]])
tensor([[-1.8300, -0.3294],
        [-3.5008, -2.9408]])
tensor([[-1.8300, -0.3294],
        [-3.5008, -2.9408]])


In [60]:
print(x)
print(y)
print(x * y)
print(torch.mul(x, y))
print(x.mul(y))

tensor([[-0.8801, -0.1596],
        [-1.4279, -1.1085]])
tensor([[0.9499, 0.1697],
        [2.0729, 1.8324]])
tensor([[-0.8361, -0.0271],
        [-2.9600, -2.0311]])
tensor([[-0.8361, -0.0271],
        [-2.9600, -2.0311]])
tensor([[-0.8361, -0.0271],
        [-2.9600, -2.0311]])


In [61]:
print(x)
print(y)
print(x / y)
print(torch.div(x, y))
print(x.div(y))

tensor([[-0.8801, -0.1596],
        [-1.4279, -1.1085]])
tensor([[0.9499, 0.1697],
        [2.0729, 1.8324]])
tensor([[-0.9265, -0.9404],
        [-0.6888, -0.6049]])
tensor([[-0.9265, -0.9404],
        [-0.6888, -0.6049]])
tensor([[-0.9265, -0.9404],
        [-0.6888, -0.6049]])


In [64]:
print(x)
print(y)
print(torch.matmul(x, y))
z = torch.mm(x, y)
print(z)
print(torch.svd(z))
print(torch.linalg.svd(z))

tensor([[-0.8801, -0.1596],
        [-1.4279, -1.1085]])
tensor([[0.9499, 0.1697],
        [2.0729, 1.8324]])
tensor([[-1.1670, -0.4419],
        [-3.6542, -2.2735]])
tensor([[-1.1670, -0.4419],
        [-3.6542, -2.2735]])
torch.return_types.svd(
U=tensor([[-0.2744, -0.9616],
        [-0.9616,  0.2744]]),
S=tensor([4.4749, 0.2320]),
V=tensor([[ 0.8568,  0.5156],
        [ 0.5156, -0.8568]]))
torch.return_types.linalg_svd(
U=tensor([[-0.2744, -0.9616],
        [-0.9616,  0.2744]]),
S=tensor([4.4749, 0.2320]),
Vh=tensor([[ 0.8568,  0.5156],
        [ 0.5156, -0.8568]]))


In [68]:
x = torch.Tensor([[1,2],
                  [3,4]])
print(x)
print(x[:,0])
print(x[:,1])
print(x[0,:])
print(x[1,:])

tensor([[1., 2.],
        [3., 4.]])
tensor([1., 3.])
tensor([2., 4.])
tensor([1., 2.])
tensor([3., 4.])


In [69]:
x = torch.randn(4, 5)
print(x)
y = x.view(20)
print(y)
z = x.view(5, -1)
print(z)

tensor([[ 1.1164,  2.6307, -1.5517,  0.8444, -1.4597],
        [-0.4919, -0.1546, -1.8296, -0.1111,  1.0954],
        [-0.0221, -0.1388, -1.0593,  0.3869, -1.4721],
        [ 0.6832,  0.4839,  1.3538, -0.7167, -0.5300]])
tensor([ 1.1164,  2.6307, -1.5517,  0.8444, -1.4597, -0.4919, -0.1546, -1.8296,
        -0.1111,  1.0954, -0.0221, -0.1388, -1.0593,  0.3869, -1.4721,  0.6832,
         0.4839,  1.3538, -0.7167, -0.5300])
tensor([[ 1.1164,  2.6307, -1.5517,  0.8444],
        [-1.4597, -0.4919, -0.1546, -1.8296],
        [-0.1111,  1.0954, -0.0221, -0.1388],
        [-1.0593,  0.3869, -1.4721,  0.6832],
        [ 0.4839,  1.3538, -0.7167, -0.5300]])


In [71]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.2677])
-0.2677339017391205
torch.float32


In [72]:
tensor = torch.rand(1, 3, 3)
print(tensor)
print(tensor.shape)

tensor([[[0.1418, 0.9463, 0.0862],
         [0.9313, 0.1812, 0.6246],
         [0.9229, 0.7695, 0.5216]]])
torch.Size([1, 3, 3])


In [87]:
t = tensor.squeeze() # 차원 축소
print(t)
print(t.shape)

tensor([[0.1418, 0.9463, 0.0862],
        [0.9313, 0.1812, 0.6246],
        [0.9229, 0.7695, 0.5216]])
torch.Size([3, 3])


In [75]:
t = torch.rand(3, 3)
print(tensor)
print(tensor.shape)

tensor([[[0.1418, 0.9463, 0.0862],
         [0.9313, 0.1812, 0.6246],
         [0.9229, 0.7695, 0.5216]]])
torch.Size([1, 3, 3])


In [91]:
t = tensor.unsqueeze(dim=0) # 차원 증가
print(t)
print(t.shape)

tensor([[[[[[0.1418, 0.9463, 0.0862],
            [0.9313, 0.1812, 0.6246],
            [0.9229, 0.7695, 0.5216]]]]]])
torch.Size([1, 1, 1, 1, 3, 3])


In [90]:
t = tensor.unsqueeze(dim=5)
print(t)
print(t.shape)

tensor([[[[[[0.1418],
            [0.9463],
            [0.0862]],

           [[0.9313],
            [0.1812],
            [0.6246]],

           [[0.9229],
            [0.7695],
            [0.5216]]]]]])
torch.Size([1, 1, 1, 3, 3, 1])


In [93]:
x = torch.FloatTensor([1,4])
print(x)
y = torch.FloatTensor([2,5])
print(y)
z = torch.FloatTensor([3,6])
print(z)

print(torch.stack([x, y, z]))

tensor([1., 4.])
tensor([2., 5.])
tensor([3., 6.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [94]:
a = torch.randn(1, 3, 3)
print(a)
b = torch.randn(1, 3, 3)
print(b)
c = torch.cat((a, b), dim=0)
print(c)
print(c.size())

tensor([[[ 2.1116, -0.9596,  0.1327],
         [ 1.2486,  1.6196,  0.0460],
         [-0.9603, -0.8097,  0.6432]]])
tensor([[[-1.6672,  1.0395,  1.1990],
         [-1.2400,  1.5860,  0.1397],
         [ 0.1473,  1.3266, -0.2905]]])
tensor([[[ 2.1116, -0.9596,  0.1327],
         [ 1.2486,  1.6196,  0.0460],
         [-0.9603, -0.8097,  0.6432]],

        [[-1.6672,  1.0395,  1.1990],
         [-1.2400,  1.5860,  0.1397],
         [ 0.1473,  1.3266, -0.2905]]])
torch.Size([2, 3, 3])


In [95]:
c = torch.cat((a, b), dim=1)
print(c)
print(c.size())

tensor([[[ 2.1116, -0.9596,  0.1327],
         [ 1.2486,  1.6196,  0.0460],
         [-0.9603, -0.8097,  0.6432],
         [-1.6672,  1.0395,  1.1990],
         [-1.2400,  1.5860,  0.1397],
         [ 0.1473,  1.3266, -0.2905]]])
torch.Size([1, 6, 3])


In [96]:
c = torch.cat((a, b), dim=2)
print(c)
print(c.size())

tensor([[[ 2.1116, -0.9596,  0.1327, -1.6672,  1.0395,  1.1990],
         [ 1.2486,  1.6196,  0.0460, -1.2400,  1.5860,  0.1397],
         [-0.9603, -0.8097,  0.6432,  0.1473,  1.3266, -0.2905]]])
torch.Size([1, 3, 6])


In [97]:
tensor = torch.rand(3, 6)
print(tensor)

t1, t2, t3 = torch.chunk(tensor, 3, dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.6141, 0.8209, 0.2088, 0.7164, 0.7295, 0.2442],
        [0.9264, 0.8866, 0.7660, 0.1550, 0.6690, 0.2030],
        [0.0284, 0.0471, 0.1818, 0.7203, 0.9267, 0.7393]])
tensor([[0.6141, 0.8209],
        [0.9264, 0.8866],
        [0.0284, 0.0471]])
tensor([[0.2088, 0.7164],
        [0.7660, 0.1550],
        [0.1818, 0.7203]])
tensor([[0.7295, 0.2442],
        [0.6690, 0.2030],
        [0.9267, 0.7393]])


In [98]:
tensor = torch.rand(3, 6)
t1, t2 = torch.split(tensor, 3, dim=1)

print(tensor)
print(t1)
print(t2)

tensor([[0.0909, 0.7104, 0.3831, 0.5859, 0.4333, 0.4761],
        [0.8639, 0.3206, 0.2925, 0.3772, 0.1727, 0.5671],
        [0.0580, 0.5874, 0.2330, 0.9042, 0.7898, 0.4520]])
tensor([[0.0909, 0.7104, 0.3831],
        [0.8639, 0.3206, 0.2925],
        [0.0580, 0.5874, 0.2330]])
tensor([[0.5859, 0.4333, 0.4761],
        [0.3772, 0.1727, 0.5671],
        [0.9042, 0.7898, 0.4520]])


In [99]:
a = torch.ones(7)
print(a)

tensor([1., 1., 1., 1., 1., 1., 1.])


In [100]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1. 1. 1.]


In [102]:
a.add_(1) # 메모리 공유
print(a)
print(b)

tensor([3., 3., 3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3. 3. 3.]


In [103]:
import numpy as np

In [104]:
a = np.ones(7)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)


In [105]:
a = torch.randn(3, 3)
a = a * 3
print(a)
print(a.requires_grad)

tensor([[-0.1308,  4.5432, -3.3892],
        [ 2.3674, -0.3935,  2.7732],
        [ 0.4041,  2.7086,  2.0598]])
False


In [3]:
import torch

In [8]:
a = torch.FloatTensor([ [1, 2],
                        [3, 4] ])
print(a)

b = torch.FloatTensor([ [5, 6],
                        [7, 8] ])
print(b)

print(a.mul_(b))
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[ 5., 12.],
        [21., 32.]])


In [13]:
print(b)
print(b.sum(dim=1))
print(b.sum(dim=0))

tensor([[5., 6.],
        [7., 8.]])
tensor([11., 15.])
tensor([12., 14.])


In [18]:
y = torch.empty(3, 4)
x = torch.ones_like(y)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [24]:
a = torch.FloatTensor([ [ [1,2,3],
                          [4,5,6],
                          [7,8,9] ],
                        [ [1,2,3],
                          [4,5,6],
                          [7,8,9] ],
                        [ [1,2,3],
                          [4,5,6],
                          [7,8,9] ] ])
print(a)
#print(a.view(9, -1))
b = a.view(27)
print(b)

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [32]:
x = torch.FloatTensor([[[1,2],
                        [3,4]]])
print(x)
print(x.size())
b = x.squeeze()
print(b)
print(b.size())
#print(x.size())

tensor([[[1., 2.],
         [3., 4.]]])
torch.Size([1, 2, 2])
tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


In [37]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                       [[5,6],
                        [7,8]],
                       [[9,10],
                        [11,12]]])
print(x)
print(x.shape)
print(x[0])
print(x[-1])

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
torch.Size([3, 2, 2])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 9., 10.],
        [11., 12.]])


In [45]:
print(x[:, 1, 0])

tensor([ 3.,  7., 11.])


In [52]:
x = torch.FloatTensor(10, 4)
print(x)
splits = x.split(4, dim=0)
#for i in splits:
#    print(i.shape)
print(splits)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
(tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]]))


In [54]:
x = torch.FloatTensor(8, 4)
print(x)
print(x.chunk(3, dim=0))

tensor([[4.5325e-17, 1.2906e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])
(tensor([[4.5325e-17, 1.2906e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]), tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]]))


In [58]:
x = torch.randn(8, 4, dtype=torch.float)
print(x)

tensor([[-1.1767,  0.2171, -0.0067,  2.3157],
        [-0.0283, -0.0633,  0.6444,  0.4157],
        [-0.1581,  0.5907,  0.9932,  0.8751],
        [-0.1787,  0.4099,  0.5122,  1.5032],
        [ 0.2181, -0.5727,  0.4776, -1.0554],
        [ 0.2306,  0.5111, -1.1738,  0.7318],
        [-0.3224, -0.7546, -0.1734,  0.6129],
        [ 0.6663, -0.0160, -0.7057, -0.7020]])


In [64]:
a = torch.FloatTensor([[1,2,3],
                        [4,5,6],
                        [7,8,9]])
b = torch.FloatTensor([[10,11,12],
                        [13,14,15],
                        [16,17,18]])
print(a)
print(b)
print(torch.cat([a,b], dim=0))
print(torch.cat([a,b], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])


In [67]:
print(torch.stack([a, b]))
print(torch.stack([a, b], dim=-1))

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])


In [68]:
result = []
for i in range(5):
    x = torch.FloatTensor(2, 2)
    result += [x]

result = torch.stack(result)
print(result)

tensor([[[1.6000e+01, 2.3694e-38],
         [2.3694e-38, 1.1252e-05]],

        [[1.5000e+01, 2.3694e-38],
         [1.1000e+01, 4.0000e+00]],

        [[1.4000e+01, 2.3694e-38],
         [3.0000e+00, 4.0000e+00]],

        [[1.3000e+01, 0.0000e+00],
         [2.3694e-38, 2.3694e-38]],

        [[1.2000e+01, 2.3694e-38],
         [3.0000e+00, 4.0000e+00]]])


In [73]:
x = torch.FloatTensor([[[1,2]],
                        [[3,4]]])
print(x.shape)

y = x.expand(2, 3, 2)
print(y.shape)
print(y)

torch.Size([2, 1, 2])
torch.Size([2, 3, 2])
tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])


In [75]:
x = torch.FloatTensor([[[1,2]],
                        [[3,4]]])
print(x.shape)

y = torch.cat([x] * 3, dim=1)
print(y)

torch.Size([2, 1, 2])
tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])


In [77]:
x = torch.randperm(10)
print(x)

tensor([5, 1, 6, 9, 8, 7, 2, 0, 3, 4])
